# ~ 301.59 MB
FROM ruby:2.6.10

# ~ 23.67 MB
# FROM ruby:2.6.10-alpine

WORKDIR "/app"

# RUN apt install build-essential

# For VS Code Ruby solargraph extension
RUN gem install solargraph

#RUN gem install benchmark-ips

COPY ./Gemfile ./

COPY ./Gemfile.lock ./

RUN bundle install
